# Generated by Django 5.0.14 on 2026-07-06 19:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("analytics", "0001_initial"),
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="generated_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="salesstatistic",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sales_stats",
                to="catalog.store",
            ),
        ),
        migrations.AddField(
            model_name="trafficstatistic",
            name="store",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="traffic_stats",
                to="catalog.store",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="salesstatistic",
            unique_together={("store", "date")},
        ),
        migrations.AlterUniqueTogether(
            name="trafficstatistic",
            unique_together={("store", "date")},
        ),
    ]
