# Generated by Django 5.0.14 on 2026-07-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="name",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur"),
                    ("merchant", "Commerçant"),
                    ("client", "Client"),
                    ("driver", "Livreur"),
                ],
                max_length=100,
                unique=True,
            ),
        ),
    ]
