# Generated by Django 5.0.14 on 2026-07-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_store_banner_store_description_store_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productimage',
            name='thumbnail_path',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
