# Generated by Django 5.0.14 on 2026-07-10 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_productimage_is_primary_productimage_thumbnail_path'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name']},
        ),
    ]
