# Generated by Django 5.0.14 on 2026-07-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_brand_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='low_stock_threshold',
            field=models.IntegerField(default=5),
        ),
    ]
