# Generated by Django 5.0.14 on 2026-07-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monetization", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="plan_type",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("premium", "Premium"),
                    ("premium_plus", "Premium+"),
                ],
                default="standard",
                max_length=20,
            ),
        ),
    ]
