/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScreensRouteImport } from './routes/screens'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScreensVerifyEmailRouteImport } from './routes/screens.verify-email'
import { Route as ScreensSplashRouteImport } from './routes/screens.splash'
import { Route as ScreensRegisterMerchantRouteImport } from './routes/screens.register-merchant'
import { Route as ScreensRegisterClientRouteImport } from './routes/screens.register-client'
import { Route as ScreensMerchantRouteImport } from './routes/screens.merchant'
import { Route as ScreensLoginRouteImport } from './routes/screens.login'
import { Route as ScreensCreateShopRouteImport } from './routes/screens.create-shop'
import { Route as ScreensCatalogRouteImport } from './routes/screens.catalog'
import { Route as ScreensAdminShopsRouteImport } from './routes/screens.admin-shops'
import { Route as ScreensAdminManagersRouteImport } from './routes/screens.admin-managers'
import { Route as ScreensAdminRouteImport } from './routes/screens.admin'
import { Route as ScreensAddProductRouteImport } from './routes/screens.add-product'

const ScreensRoute = ScreensRouteImport.update({
  id: '/screens',
  path: '/screens',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreensVerifyEmailRoute = ScreensVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensSplashRoute = ScreensSplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensRegisterMerchantRoute = ScreensRegisterMerchantRouteImport.update({
  id: '/register-merchant',
  path: '/register-merchant',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensRegisterClientRoute = ScreensRegisterClientRouteImport.update({
  id: '/register-client',
  path: '/register-client',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensMerchantRoute = ScreensMerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensLoginRoute = ScreensLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensCreateShopRoute = ScreensCreateShopRouteImport.update({
  id: '/create-shop',
  path: '/create-shop',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensCatalogRoute = ScreensCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensAdminShopsRoute = ScreensAdminShopsRouteImport.update({
  id: '/admin-shops',
  path: '/admin-shops',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensAdminManagersRoute = ScreensAdminManagersRouteImport.update({
  id: '/admin-managers',
  path: '/admin-managers',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensAdminRoute = ScreensAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensAddProductRoute = ScreensAddProductRouteImport.update({
  id: '/add-product',
  path: '/add-product',
  getParentRoute: () => ScreensRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/screens': typeof ScreensRouteWithChildren
  '/screens/add-product': typeof ScreensAddProductRoute
  '/screens/admin': typeof ScreensAdminRoute
  '/screens/admin-managers': typeof ScreensAdminManagersRoute
  '/screens/admin-shops': typeof ScreensAdminShopsRoute
  '/screens/catalog': typeof ScreensCatalogRoute
  '/screens/create-shop': typeof ScreensCreateShopRoute
  '/screens/login': typeof ScreensLoginRoute
  '/screens/merchant': typeof ScreensMerchantRoute
  '/screens/register-client': typeof ScreensRegisterClientRoute
  '/screens/register-merchant': typeof ScreensRegisterMerchantRoute
  '/screens/splash': typeof ScreensSplashRoute
  '/screens/verify-email': typeof ScreensVerifyEmailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/screens': typeof ScreensRouteWithChildren
  '/screens/add-product': typeof ScreensAddProductRoute
  '/screens/admin': typeof ScreensAdminRoute
  '/screens/admin-managers': typeof ScreensAdminManagersRoute
  '/screens/admin-shops': typeof ScreensAdminShopsRoute
  '/screens/catalog': typeof ScreensCatalogRoute
  '/screens/create-shop': typeof ScreensCreateShopRoute
  '/screens/login': typeof ScreensLoginRoute
  '/screens/merchant': typeof ScreensMerchantRoute
  '/screens/register-client': typeof ScreensRegisterClientRoute
  '/screens/register-merchant': typeof ScreensRegisterMerchantRoute
  '/screens/splash': typeof ScreensSplashRoute
  '/screens/verify-email': typeof ScreensVerifyEmailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/screens': typeof ScreensRouteWithChildren
  '/screens/add-product': typeof ScreensAddProductRoute
  '/screens/admin': typeof ScreensAdminRoute
  '/screens/admin-managers': typeof ScreensAdminManagersRoute
  '/screens/admin-shops': typeof ScreensAdminShopsRoute
  '/screens/catalog': typeof ScreensCatalogRoute
  '/screens/create-shop': typeof ScreensCreateShopRoute
  '/screens/login': typeof ScreensLoginRoute
  '/screens/merchant': typeof ScreensMerchantRoute
  '/screens/register-client': typeof ScreensRegisterClientRoute
  '/screens/register-merchant': typeof ScreensRegisterMerchantRoute
  '/screens/splash': typeof ScreensSplashRoute
  '/screens/verify-email': typeof ScreensVerifyEmailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/screens'
    | '/screens/add-product'
    | '/screens/admin'
    | '/screens/admin-managers'
    | '/screens/admin-shops'
    | '/screens/catalog'
    | '/screens/create-shop'
    | '/screens/login'
    | '/screens/merchant'
    | '/screens/register-client'
    | '/screens/register-merchant'
    | '/screens/splash'
    | '/screens/verify-email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/screens'
    | '/screens/add-product'
    | '/screens/admin'
    | '/screens/admin-managers'
    | '/screens/admin-shops'
    | '/screens/catalog'
    | '/screens/create-shop'
    | '/screens/login'
    | '/screens/merchant'
    | '/screens/register-client'
    | '/screens/register-merchant'
    | '/screens/splash'
    | '/screens/verify-email'
  id:
    | '__root__'
    | '/'
    | '/screens'
    | '/screens/add-product'
    | '/screens/admin'
    | '/screens/admin-managers'
    | '/screens/admin-shops'
    | '/screens/catalog'
    | '/screens/create-shop'
    | '/screens/login'
    | '/screens/merchant'
    | '/screens/register-client'
    | '/screens/register-merchant'
    | '/screens/splash'
    | '/screens/verify-email'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScreensRoute: typeof ScreensRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/screens': {
      id: '/screens'
      path: '/screens'
      fullPath: '/screens'
      preLoaderRoute: typeof ScreensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screens/verify-email': {
      id: '/screens/verify-email'
      path: '/verify-email'
      fullPath: '/screens/verify-email'
      preLoaderRoute: typeof ScreensVerifyEmailRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/splash': {
      id: '/screens/splash'
      path: '/splash'
      fullPath: '/screens/splash'
      preLoaderRoute: typeof ScreensSplashRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/register-merchant': {
      id: '/screens/register-merchant'
      path: '/register-merchant'
      fullPath: '/screens/register-merchant'
      preLoaderRoute: typeof ScreensRegisterMerchantRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/register-client': {
      id: '/screens/register-client'
      path: '/register-client'
      fullPath: '/screens/register-client'
      preLoaderRoute: typeof ScreensRegisterClientRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/merchant': {
      id: '/screens/merchant'
      path: '/merchant'
      fullPath: '/screens/merchant'
      preLoaderRoute: typeof ScreensMerchantRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/login': {
      id: '/screens/login'
      path: '/login'
      fullPath: '/screens/login'
      preLoaderRoute: typeof ScreensLoginRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/create-shop': {
      id: '/screens/create-shop'
      path: '/create-shop'
      fullPath: '/screens/create-shop'
      preLoaderRoute: typeof ScreensCreateShopRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/catalog': {
      id: '/screens/catalog'
      path: '/catalog'
      fullPath: '/screens/catalog'
      preLoaderRoute: typeof ScreensCatalogRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/admin-shops': {
      id: '/screens/admin-shops'
      path: '/admin-shops'
      fullPath: '/screens/admin-shops'
      preLoaderRoute: typeof ScreensAdminShopsRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/admin-managers': {
      id: '/screens/admin-managers'
      path: '/admin-managers'
      fullPath: '/screens/admin-managers'
      preLoaderRoute: typeof ScreensAdminManagersRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/admin': {
      id: '/screens/admin'
      path: '/admin'
      fullPath: '/screens/admin'
      preLoaderRoute: typeof ScreensAdminRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/add-product': {
      id: '/screens/add-product'
      path: '/add-product'
      fullPath: '/screens/add-product'
      preLoaderRoute: typeof ScreensAddProductRouteImport
      parentRoute: typeof ScreensRoute
    }
  }
}

interface ScreensRouteChildren {
  ScreensAddProductRoute: typeof ScreensAddProductRoute
  ScreensAdminRoute: typeof ScreensAdminRoute
  ScreensAdminManagersRoute: typeof ScreensAdminManagersRoute
  ScreensAdminShopsRoute: typeof ScreensAdminShopsRoute
  ScreensCatalogRoute: typeof ScreensCatalogRoute
  ScreensCreateShopRoute: typeof ScreensCreateShopRoute
  ScreensLoginRoute: typeof ScreensLoginRoute
  ScreensMerchantRoute: typeof ScreensMerchantRoute
  ScreensRegisterClientRoute: typeof ScreensRegisterClientRoute
  ScreensRegisterMerchantRoute: typeof ScreensRegisterMerchantRoute
  ScreensSplashRoute: typeof ScreensSplashRoute
  ScreensVerifyEmailRoute: typeof ScreensVerifyEmailRoute
}

const ScreensRouteChildren: ScreensRouteChildren = {
  ScreensAddProductRoute: ScreensAddProductRoute,
  ScreensAdminRoute: ScreensAdminRoute,
  ScreensAdminManagersRoute: ScreensAdminManagersRoute,
  ScreensAdminShopsRoute: ScreensAdminShopsRoute,
  ScreensCatalogRoute: ScreensCatalogRoute,
  ScreensCreateShopRoute: ScreensCreateShopRoute,
  ScreensLoginRoute: ScreensLoginRoute,
  ScreensMerchantRoute: ScreensMerchantRoute,
  ScreensRegisterClientRoute: ScreensRegisterClientRoute,
  ScreensRegisterMerchantRoute: ScreensRegisterMerchantRoute,
  ScreensSplashRoute: ScreensSplashRoute,
  ScreensVerifyEmailRoute: ScreensVerifyEmailRoute,
}

const ScreensRouteWithChildren =
  ScreensRoute._addFileChildren(ScreensRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScreensRoute: ScreensRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
