/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScreensRouteImport } from './routes/screens'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScreensWishlistRouteImport } from './routes/screens.wishlist'
import { Route as ScreensVerifyEmailRouteImport } from './routes/screens.verify-email'
import { Route as ScreensSplashRouteImport } from './routes/screens.splash'
import { Route as ScreensSearchRouteImport } from './routes/screens.search'
import { Route as ScreensRegisterMerchantRouteImport } from './routes/screens.register-merchant'
import { Route as ScreensRegisterClientRouteImport } from './routes/screens.register-client'
import { Route as ScreensProductRouteImport } from './routes/screens.product'
import { Route as ScreensOrderConfirmedRouteImport } from './routes/screens.order-confirmed'
import { Route as ScreensMerchantRouteImport } from './routes/screens.merchant'
import { Route as ScreensLoginRouteImport } from './routes/screens.login'
import { Route as ScreensHomeRouteImport } from './routes/screens.home'
import { Route as ScreensCreateShopRouteImport } from './routes/screens.create-shop'
import { Route as ScreensCheckoutPaymentRouteImport } from './routes/screens.checkout-payment'
import { Route as ScreensCheckoutDeliveryRouteImport } from './routes/screens.checkout-delivery'
import { Route as ScreensCheckoutAddressRouteImport } from './routes/screens.checkout-address'
import { Route as ScreensCatalogRouteImport } from './routes/screens.catalog'
import { Route as ScreensCartRouteImport } from './routes/screens.cart'
import { Route as ScreensAdminShopsRouteImport } from './routes/screens.admin-shops'
import { Route as ScreensAdminManagersRouteImport } from './routes/screens.admin-managers'
import { Route as ScreensAdminRouteImport } from './routes/screens.admin'
import { Route as ScreensAddProductRouteImport } from './routes/screens.add-product'

const ScreensRoute = ScreensRouteImport.update({
  id: '/screens',
  path: '/screens',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreensWishlistRoute = ScreensWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensVerifyEmailRoute = ScreensVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensSplashRoute = ScreensSplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensSearchRoute = ScreensSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensRegisterMerchantRoute = ScreensRegisterMerchantRouteImport.update({
  id: '/register-merchant',
  path: '/register-merchant',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensRegisterClientRoute = ScreensRegisterClientRouteImport.update({
  id: '/register-client',
  path: '/register-client',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensProductRoute = ScreensProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensOrderConfirmedRoute = ScreensOrderConfirmedRouteImport.update({
  id: '/order-confirmed',
  path: '/order-confirmed',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensMerchantRoute = ScreensMerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensLoginRoute = ScreensLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensHomeRoute = ScreensHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensCreateShopRoute = ScreensCreateShopRouteImport.update({
  id: '/create-shop',
  path: '/create-shop',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensCheckoutPaymentRoute = ScreensCheckoutPaymentRouteImport.update({
  id: '/checkout-payment',
  path: '/checkout-payment',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensCheckoutDeliveryRoute = ScreensCheckoutDeliveryRouteImport.update({
  id: '/checkout-delivery',
  path: '/checkout-delivery',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensCheckoutAddressRoute = ScreensCheckoutAddressRouteImport.update({
  id: '/checkout-address',
  path: '/checkout-address',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensCatalogRoute = ScreensCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensCartRoute = ScreensCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensAdminShopsRoute = ScreensAdminShopsRouteImport.update({
  id: '/admin-shops',
  path: '/admin-shops',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensAdminManagersRoute = ScreensAdminManagersRouteImport.update({
  id: '/admin-managers',
  path: '/admin-managers',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensAdminRoute = ScreensAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ScreensRoute,
} as any)
const ScreensAddProductRoute = ScreensAddProductRouteImport.update({
  id: '/add-product',
  path: '/add-product',
  getParentRoute: () => ScreensRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/screens': typeof ScreensRouteWithChildren
  '/screens/add-product': typeof ScreensAddProductRoute
  '/screens/admin': typeof ScreensAdminRoute
  '/screens/admin-managers': typeof ScreensAdminManagersRoute
  '/screens/admin-shops': typeof ScreensAdminShopsRoute
  '/screens/cart': typeof ScreensCartRoute
  '/screens/catalog': typeof ScreensCatalogRoute
  '/screens/checkout-address': typeof ScreensCheckoutAddressRoute
  '/screens/checkout-delivery': typeof ScreensCheckoutDeliveryRoute
  '/screens/checkout-payment': typeof ScreensCheckoutPaymentRoute
  '/screens/create-shop': typeof ScreensCreateShopRoute
  '/screens/home': typeof ScreensHomeRoute
  '/screens/login': typeof ScreensLoginRoute
  '/screens/merchant': typeof ScreensMerchantRoute
  '/screens/order-confirmed': typeof ScreensOrderConfirmedRoute
  '/screens/product': typeof ScreensProductRoute
  '/screens/register-client': typeof ScreensRegisterClientRoute
  '/screens/register-merchant': typeof ScreensRegisterMerchantRoute
  '/screens/search': typeof ScreensSearchRoute
  '/screens/splash': typeof ScreensSplashRoute
  '/screens/verify-email': typeof ScreensVerifyEmailRoute
  '/screens/wishlist': typeof ScreensWishlistRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/screens': typeof ScreensRouteWithChildren
  '/screens/add-product': typeof ScreensAddProductRoute
  '/screens/admin': typeof ScreensAdminRoute
  '/screens/admin-managers': typeof ScreensAdminManagersRoute
  '/screens/admin-shops': typeof ScreensAdminShopsRoute
  '/screens/cart': typeof ScreensCartRoute
  '/screens/catalog': typeof ScreensCatalogRoute
  '/screens/checkout-address': typeof ScreensCheckoutAddressRoute
  '/screens/checkout-delivery': typeof ScreensCheckoutDeliveryRoute
  '/screens/checkout-payment': typeof ScreensCheckoutPaymentRoute
  '/screens/create-shop': typeof ScreensCreateShopRoute
  '/screens/home': typeof ScreensHomeRoute
  '/screens/login': typeof ScreensLoginRoute
  '/screens/merchant': typeof ScreensMerchantRoute
  '/screens/order-confirmed': typeof ScreensOrderConfirmedRoute
  '/screens/product': typeof ScreensProductRoute
  '/screens/register-client': typeof ScreensRegisterClientRoute
  '/screens/register-merchant': typeof ScreensRegisterMerchantRoute
  '/screens/search': typeof ScreensSearchRoute
  '/screens/splash': typeof ScreensSplashRoute
  '/screens/verify-email': typeof ScreensVerifyEmailRoute
  '/screens/wishlist': typeof ScreensWishlistRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/screens': typeof ScreensRouteWithChildren
  '/screens/add-product': typeof ScreensAddProductRoute
  '/screens/admin': typeof ScreensAdminRoute
  '/screens/admin-managers': typeof ScreensAdminManagersRoute
  '/screens/admin-shops': typeof ScreensAdminShopsRoute
  '/screens/cart': typeof ScreensCartRoute
  '/screens/catalog': typeof ScreensCatalogRoute
  '/screens/checkout-address': typeof ScreensCheckoutAddressRoute
  '/screens/checkout-delivery': typeof ScreensCheckoutDeliveryRoute
  '/screens/checkout-payment': typeof ScreensCheckoutPaymentRoute
  '/screens/create-shop': typeof ScreensCreateShopRoute
  '/screens/home': typeof ScreensHomeRoute
  '/screens/login': typeof ScreensLoginRoute
  '/screens/merchant': typeof ScreensMerchantRoute
  '/screens/order-confirmed': typeof ScreensOrderConfirmedRoute
  '/screens/product': typeof ScreensProductRoute
  '/screens/register-client': typeof ScreensRegisterClientRoute
  '/screens/register-merchant': typeof ScreensRegisterMerchantRoute
  '/screens/search': typeof ScreensSearchRoute
  '/screens/splash': typeof ScreensSplashRoute
  '/screens/verify-email': typeof ScreensVerifyEmailRoute
  '/screens/wishlist': typeof ScreensWishlistRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/screens'
    | '/screens/add-product'
    | '/screens/admin'
    | '/screens/admin-managers'
    | '/screens/admin-shops'
    | '/screens/cart'
    | '/screens/catalog'
    | '/screens/checkout-address'
    | '/screens/checkout-delivery'
    | '/screens/checkout-payment'
    | '/screens/create-shop'
    | '/screens/home'
    | '/screens/login'
    | '/screens/merchant'
    | '/screens/order-confirmed'
    | '/screens/product'
    | '/screens/register-client'
    | '/screens/register-merchant'
    | '/screens/search'
    | '/screens/splash'
    | '/screens/verify-email'
    | '/screens/wishlist'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/screens'
    | '/screens/add-product'
    | '/screens/admin'
    | '/screens/admin-managers'
    | '/screens/admin-shops'
    | '/screens/cart'
    | '/screens/catalog'
    | '/screens/checkout-address'
    | '/screens/checkout-delivery'
    | '/screens/checkout-payment'
    | '/screens/create-shop'
    | '/screens/home'
    | '/screens/login'
    | '/screens/merchant'
    | '/screens/order-confirmed'
    | '/screens/product'
    | '/screens/register-client'
    | '/screens/register-merchant'
    | '/screens/search'
    | '/screens/splash'
    | '/screens/verify-email'
    | '/screens/wishlist'
  id:
    | '__root__'
    | '/'
    | '/screens'
    | '/screens/add-product'
    | '/screens/admin'
    | '/screens/admin-managers'
    | '/screens/admin-shops'
    | '/screens/cart'
    | '/screens/catalog'
    | '/screens/checkout-address'
    | '/screens/checkout-delivery'
    | '/screens/checkout-payment'
    | '/screens/create-shop'
    | '/screens/home'
    | '/screens/login'
    | '/screens/merchant'
    | '/screens/order-confirmed'
    | '/screens/product'
    | '/screens/register-client'
    | '/screens/register-merchant'
    | '/screens/search'
    | '/screens/splash'
    | '/screens/verify-email'
    | '/screens/wishlist'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScreensRoute: typeof ScreensRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/screens': {
      id: '/screens'
      path: '/screens'
      fullPath: '/screens'
      preLoaderRoute: typeof ScreensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screens/wishlist': {
      id: '/screens/wishlist'
      path: '/wishlist'
      fullPath: '/screens/wishlist'
      preLoaderRoute: typeof ScreensWishlistRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/verify-email': {
      id: '/screens/verify-email'
      path: '/verify-email'
      fullPath: '/screens/verify-email'
      preLoaderRoute: typeof ScreensVerifyEmailRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/splash': {
      id: '/screens/splash'
      path: '/splash'
      fullPath: '/screens/splash'
      preLoaderRoute: typeof ScreensSplashRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/search': {
      id: '/screens/search'
      path: '/search'
      fullPath: '/screens/search'
      preLoaderRoute: typeof ScreensSearchRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/register-merchant': {
      id: '/screens/register-merchant'
      path: '/register-merchant'
      fullPath: '/screens/register-merchant'
      preLoaderRoute: typeof ScreensRegisterMerchantRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/register-client': {
      id: '/screens/register-client'
      path: '/register-client'
      fullPath: '/screens/register-client'
      preLoaderRoute: typeof ScreensRegisterClientRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/product': {
      id: '/screens/product'
      path: '/product'
      fullPath: '/screens/product'
      preLoaderRoute: typeof ScreensProductRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/order-confirmed': {
      id: '/screens/order-confirmed'
      path: '/order-confirmed'
      fullPath: '/screens/order-confirmed'
      preLoaderRoute: typeof ScreensOrderConfirmedRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/merchant': {
      id: '/screens/merchant'
      path: '/merchant'
      fullPath: '/screens/merchant'
      preLoaderRoute: typeof ScreensMerchantRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/login': {
      id: '/screens/login'
      path: '/login'
      fullPath: '/screens/login'
      preLoaderRoute: typeof ScreensLoginRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/home': {
      id: '/screens/home'
      path: '/home'
      fullPath: '/screens/home'
      preLoaderRoute: typeof ScreensHomeRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/create-shop': {
      id: '/screens/create-shop'
      path: '/create-shop'
      fullPath: '/screens/create-shop'
      preLoaderRoute: typeof ScreensCreateShopRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/checkout-payment': {
      id: '/screens/checkout-payment'
      path: '/checkout-payment'
      fullPath: '/screens/checkout-payment'
      preLoaderRoute: typeof ScreensCheckoutPaymentRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/checkout-delivery': {
      id: '/screens/checkout-delivery'
      path: '/checkout-delivery'
      fullPath: '/screens/checkout-delivery'
      preLoaderRoute: typeof ScreensCheckoutDeliveryRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/checkout-address': {
      id: '/screens/checkout-address'
      path: '/checkout-address'
      fullPath: '/screens/checkout-address'
      preLoaderRoute: typeof ScreensCheckoutAddressRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/catalog': {
      id: '/screens/catalog'
      path: '/catalog'
      fullPath: '/screens/catalog'
      preLoaderRoute: typeof ScreensCatalogRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/cart': {
      id: '/screens/cart'
      path: '/cart'
      fullPath: '/screens/cart'
      preLoaderRoute: typeof ScreensCartRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/admin-shops': {
      id: '/screens/admin-shops'
      path: '/admin-shops'
      fullPath: '/screens/admin-shops'
      preLoaderRoute: typeof ScreensAdminShopsRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/admin-managers': {
      id: '/screens/admin-managers'
      path: '/admin-managers'
      fullPath: '/screens/admin-managers'
      preLoaderRoute: typeof ScreensAdminManagersRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/admin': {
      id: '/screens/admin'
      path: '/admin'
      fullPath: '/screens/admin'
      preLoaderRoute: typeof ScreensAdminRouteImport
      parentRoute: typeof ScreensRoute
    }
    '/screens/add-product': {
      id: '/screens/add-product'
      path: '/add-product'
      fullPath: '/screens/add-product'
      preLoaderRoute: typeof ScreensAddProductRouteImport
      parentRoute: typeof ScreensRoute
    }
  }
}

interface ScreensRouteChildren {
  ScreensAddProductRoute: typeof ScreensAddProductRoute
  ScreensAdminRoute: typeof ScreensAdminRoute
  ScreensAdminManagersRoute: typeof ScreensAdminManagersRoute
  ScreensAdminShopsRoute: typeof ScreensAdminShopsRoute
  ScreensCartRoute: typeof ScreensCartRoute
  ScreensCatalogRoute: typeof ScreensCatalogRoute
  ScreensCheckoutAddressRoute: typeof ScreensCheckoutAddressRoute
  ScreensCheckoutDeliveryRoute: typeof ScreensCheckoutDeliveryRoute
  ScreensCheckoutPaymentRoute: typeof ScreensCheckoutPaymentRoute
  ScreensCreateShopRoute: typeof ScreensCreateShopRoute
  ScreensHomeRoute: typeof ScreensHomeRoute
  ScreensLoginRoute: typeof ScreensLoginRoute
  ScreensMerchantRoute: typeof ScreensMerchantRoute
  ScreensOrderConfirmedRoute: typeof ScreensOrderConfirmedRoute
  ScreensProductRoute: typeof ScreensProductRoute
  ScreensRegisterClientRoute: typeof ScreensRegisterClientRoute
  ScreensRegisterMerchantRoute: typeof ScreensRegisterMerchantRoute
  ScreensSearchRoute: typeof ScreensSearchRoute
  ScreensSplashRoute: typeof ScreensSplashRoute
  ScreensVerifyEmailRoute: typeof ScreensVerifyEmailRoute
  ScreensWishlistRoute: typeof ScreensWishlistRoute
}

const ScreensRouteChildren: ScreensRouteChildren = {
  ScreensAddProductRoute: ScreensAddProductRoute,
  ScreensAdminRoute: ScreensAdminRoute,
  ScreensAdminManagersRoute: ScreensAdminManagersRoute,
  ScreensAdminShopsRoute: ScreensAdminShopsRoute,
  ScreensCartRoute: ScreensCartRoute,
  ScreensCatalogRoute: ScreensCatalogRoute,
  ScreensCheckoutAddressRoute: ScreensCheckoutAddressRoute,
  ScreensCheckoutDeliveryRoute: ScreensCheckoutDeliveryRoute,
  ScreensCheckoutPaymentRoute: ScreensCheckoutPaymentRoute,
  ScreensCreateShopRoute: ScreensCreateShopRoute,
  ScreensHomeRoute: ScreensHomeRoute,
  ScreensLoginRoute: ScreensLoginRoute,
  ScreensMerchantRoute: ScreensMerchantRoute,
  ScreensOrderConfirmedRoute: ScreensOrderConfirmedRoute,
  ScreensProductRoute: ScreensProductRoute,
  ScreensRegisterClientRoute: ScreensRegisterClientRoute,
  ScreensRegisterMerchantRoute: ScreensRegisterMerchantRoute,
  ScreensSearchRoute: ScreensSearchRoute,
  ScreensSplashRoute: ScreensSplashRoute,
  ScreensVerifyEmailRoute: ScreensVerifyEmailRoute,
  ScreensWishlistRoute: ScreensWishlistRoute,
}

const ScreensRouteWithChildren =
  ScreensRoute._addFileChildren(ScreensRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScreensRoute: ScreensRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
